### ISSUE TITLE
Non premium users can see only the first 10 jobs

### ISSUE THREAD

**Issue by Wilfredoo** [Wilfredoo/newJobdirecto#19]

**Comment by jneidel** [comment]
premium user === logged-in people?

**Comment by Wilfredoo** [comment]
nope, premium user is someone who pays, let's say, 2 euros a week. This is a monetization move that I want to try.

**Comment by jneidel** [comment]
Okay, but then 10 jobs for non-premiums is really restrictive.

And this could be a move that turns the users against you.
