### ISSUE TITLE
Add new regions

### ISSUE THREAD

**Issue by Wilfredoo** [Wilfredoo/newJobdirecto#6]
Let's expand JobDirecto to a new city.

We can do a test with New Jersey.

**Comment by jneidel** [comment]
In my eyes there are two approaches of doing this:

1. Separate sub-domains for each region (ny.jobdirecto.com, nj.jobdirecto.com, etc.)
2. Welcome page, where user picks the region (drop-down: New York, New Jersey, etc)

Advantages for 1:

- More direct (bookmarks keep their region)
- Easier to scale later on (domains are easy to split on multiple servers)
- Still has the drop-down to choose another region, while keeping it's advantages

Advantages for 2:

- Less work (1 need a basic version of 2 as well)
- Easier to scale in the beginning (just an add-on to the website, no dns/server config)

As a solution I like 1. better but it's something we can also add later on, as it requires much of the functionality of 2.

**Comment by Wilfredoo** [comment]
Approach 1 pls!
