### ISSUE TITLE
Inconsitent translation

### ISSUE THREAD

**Issue by jneidel** [Wilfredoo/newJobdirecto#8]
While looking at the site in English I found a few spots are not translated:
- report job button and description
- the "I'm looking for a job" form

**Comment by Wilfredoo** [comment]
1.- Report job must be translated.
2.- "I'm looking for a job" doesn't need to be translated, that section is just for Spanish speakers.

**Comment by jneidel** [comment]
It's fixed?

If so please link in the commit description to this PR like so: `fixes #8` or `Closes #8`
